/* ═══════════════════════════════════════════════════════════
   solution.js — a detector that works

   Not what the app opens with. editor.js ships an empty
   process_block, because writing it is the exercise; this
   is here to check your own against, and the app reaches
   for it only when the page is opened with ?solution=1.
   start-solution.cmd does that for you.

   solution.py is the same detector, for the bench that
   lives in detector.py.
   ═══════════════════════════════════════════════════════════ */

window.DTMF_SOLUTION = [
    '# ── What the app gives you ─────────────────────────────────────────',
    '#',
    '# The five names below belong to the app: it binds them before your',
    '# code runs and again after it, so changing the numbers here changes',
    '# nothing. The keypad sends at FS, and process_block is handed BLOCK',
    '# samples at a time.',
    '',
    'FS = 8000                            # sample rate, Hz',
    'BLOCK = 256                          # samples per call — 32.0 ms',
    '',
    'ROW_HZ = (697, 770, 852, 941)        # the four rows, top to bottom',
    'COL_HZ = (1209, 1336, 1477, 1633)    # the four columns, left to right',
    '',
    "KEYS = (('1', '2', '3', 'A'),        # KEYS[row][col] — where they cross",
    "        ('4', '5', '6', 'B'),",
    "        ('7', '8', '9', 'C'),",
    "        ('*', '0', '#', 'D'))",
    '',
    '',
    '# ── The detector ───────────────────────────────────────────────────',
    '',
    'import math',
    '',
    'import numpy as np',
    '',
    '',
    'def goertzel(samples, f, fs):',
    '    """|X(f)|^2 over one block, by the two-pole recursion.',
    '',
    '    One frequency, not a whole transform: eight of these',
    '    cost far less than an FFT whose outputs would all but',
    '    eight be thrown away. Evaluated at f itself and not at',
    '    the nearest DFT bin, which can cost 4 dB of the very',
    '    magnitude being measured.',
    '    """',
    '    w = 2.0 * math.pi * f / fs',
    '    coeff = 2.0 * math.cos(w)',
    '    s1 = s2 = 0.0',
    '    for v in samples:',
    '        s0 = v + coeff * s1 - s2',
    '        s2 = s1',
    '        s1 = s0',
    '    return s1 * s1 + s2 * s2 - coeff * s1 * s2',
    '',
    '',
    'def tone_power(samples, f, fs):',
    '    """Mean power of the component at f: A^2/2 for a sine of',
    '       amplitude A, so it compares directly with the mean',
    '       power of the block itself."""',
    '    n = len(samples)',
    '    return 2.0 * goertzel(samples, f, fs) / (n * n)',
    '',
    '',
    'def runner_up(vals, win):',
    '    """The largest of the rest — what the winner has to beat."""',
    '    return max(v for i, v in enumerate(vals) if i != win)',
    '',
    '',
    'QUIET = 1e-5      # mean power below which the line counts as silent',
    'RATIO = 8.0       # how far the winning tone must beat its runner-up',
    'PURITY = 0.5      # share of the block the two tones must account for',
    'TWIST = 10.0      # widest power ratio between the two tones — about',
    '                  # 10 dB, past which this gives up. Push the twist',
    '                  # slider further than that and watch it do so.',
    '',
    '',
    'def process_block(x, fs, buf_size):',
    '    """One block of the line in, one character out — or None.',
    '',
    '    Called once per block for as long as the app is running.',
    '    This is the one name the app looks for: delete it and Run',
    '    will tell you so.',
    '',
    '    Every path out of here hands back the eight powers as well',
    '    as the answer, so the Spectrum panel can draw what the',
    '    decision was made from — including the times it decides',
    '    there is nothing there.',
    '    """',
    '    power = float(np.mean(x * x))',
    '',
    '    # a Python loop over a numpy array pays for a boxed float a step',
    '    samples = x.tolist()',
    '    rows = [tone_power(samples, f, fs) for f in ROW_HZ]',
    '    cols = [tone_power(samples, f, fs) for f in COL_HZ]',
    '    stems = rows + cols',
    '',
    '    # The quiet gate used to return before measuring anything, which is',
    '    # the cheaper order. It measures first now so that the panel has',
    '    # something to draw between digits — and a block that is below the',
    '    # gate is a block with time to spare.',
    '    if power < QUIET:',
    '        return None, stems               # nothing on the line',
    '',
    '    r = max(range(4), key=lambda i: rows[i])',
    '    c = max(range(4), key=lambda i: cols[i])',
    '',
    '    # one tone per group, each well clear of the other three',
    '    if runner_up(rows, r) * RATIO > rows[r]:',
    '        return None, stems',
    '    if runner_up(cols, c) * RATIO > cols[c]:',
    '        return None, stems',
    '',
    '    # the pair has to be most of what is in the block, or it is noise',
    '    # that happens to lean one way',
    '    if rows[r] + cols[c] < PURITY * power:',
    '        return None, stems',
    '',
    '    # and neither tone may swamp the other: that is twist, and a real',
    '    # line has a few dB of it, never twenty',
    '    if not (1.0 / TWIST < cols[c] / rows[r] < TWIST):',
    '        return None, stems',
    '',
    '    return KEYS[r][c], stems',
    '',
].join('\n');
